### PR TITLE
Add staticTimestamp option

### PR DESCRIPTION
**Pull request by greypants**
Allows identical recompiles from an unchanged source file.

Resovles #33

### CODE REVIEW

**Comment by puzrin** [comment]
I like idea in general, but would like more accurate implementation.

Please do it as `--ts Number`, check that it will not break default bnehaviour and i'll be glad to merge it.

**Comment by greypants** [comment]
How's that look? Let me know if you want me to squash these too commits together.

**Comment by puzrin** [comment]
Yes, please squash those into one.

**Comment by greypants** [comment]
Squashed.

**Comment by greypants** [comment]
Ok, everything should be addressed.

**Comment by greypants** [comment]
Anything left to do here?

**Comment by puzrin** [comment]
Closed via https://github.com/fontello/svg2ttf/commit/93fc07a626301268993c9441831d94bed8c59e7f . I did a bit more accurate implementation.

**Comment by greypants** [comment]
great, thanks!

**Pull request closed without merging**
