### PR TITLE
Fix IE ligatures by explicitly adding the latin script to the script list

### PR DESCRIPTION
**Pull request by sabberworm**
Apparently it seems to be important to explicitly mention the `latn` script for ligatures on western characters, even though the fallback (`DFLT`) should be enough.

I had the problem where IE would not display any ligatures and Firefox would bail on some as well. This fixes all of these cases. I haven’t tried to add non-latin ligatures, though. Maybe we’ll need to add other script identifiers as well…

I checked icomoon.io output and they only insert `latn`. So we’re already better if we use both `latn` and `DFLT`.

### CODE REVIEW

**Comment by puzrin** [comment]
Thank you! Should i release immediately or more changes planned?

**Comment by sabberworm** [comment]
No, I don’t have any time in the near future and also I don’t currently see any issues I can resolve.

**Comment by sabberworm** [comment]
@puzrin Sorry, my last message was a bit confusing. What I meant to say was: yes, please release and no, no more changes are planned…

**Comment by puzrin** [comment]
Published, sorry for delay

**Pull request merged**
