### PR TITLE
fsType as a font option

### PR DESCRIPTION
**Pull request by emalgholzad**

### CODE REVIEW

**Comment by puzrin** [comment]
Reasons? SVG source has no such info.

**Comment by tijmenvangurp** [comment]
@puzrin You are correct but a TTF can have such info. Creating a TTF font from an SVG source it might be required to set this.
http://www.typophile.com/node/18777

**Comment by puzrin** [comment]
That does not answer question, why such functionality should be in this package. People can write ttf updater separately to change any possible options, or even fork this project and to anything they can imagine. But i don'e see why this is related to simplified SVG convertor. This option looks stange in API, IMHO.

**Comment by tommyka** [comment]
The reason to have that option is that you get a error in IE11 if then font files don´t have a permission to be used as a embedded font.

The current default causes the following error in IE11 ```@font-face failed OpenType embedding permission check. Permission must be Installable.```

Please consider merging this pull request

**Comment by puzrin** [comment]
Current defaults were ok with IE11 (if MS did not changed anything). Anyway, fixing defaults is not the same as adding new option.

**Comment by puzrin** [comment]
After check - argument about broken IE11 seems invalid, that was fixed in #45 many years ago.

**Comment by puzrin** [comment]
Close - not enougth reasons.

**Pull request closed without merging**
